### ISSUE TITLE
抛出异常

### ISSUE THREAD

**Issue by baixuecheng** [liunewshine/spring-boot-template#1]
您好，我clone之后，为什么就是抛出异常前台接受不到呢？ 比如  密码输错，他也只是弹出那个错误提示，但是不提示是因为密码输错
![ASQ_8CHZKV@L~ 5`H} {4S](https://user-images.githubusercontent.com/44012446/91732016-38689f80-ebda-11ea-81c7-f860d308d9b8.png)

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/91732869-6a2e3600-ebdb-11ea-95fa-96bdd4c7f1c0.png)
spring boot 2.3.0以后需要配置文件中增加
`server.error.include-message=always`
才可正常显示消息

**Comment by baixuecheng** [comment]
十分感激，谢谢您的项目
